SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 100
  LR: 0.0001
  SEED: 42
DA:
  TASK: False
  USE: False

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "CATDTI_Vanilla"
  TAG: "Non_DA"

