SOLVER:
#  BATCH_SIZE: 32
  BATCH_SIZE: 16
  MAX_EPOCH: 100
  LR: 1e-4
  DA_LR: 5e-5
  SEED: 42
DA:
  TASK: True
  USE: True
  METHOD: "CDAN"
  USE_ENTROPY: False
  RANDOM_LAYER: True
  ORIGINAL_RANDOM: True
  RANDOM_DIM: 256
  INIT_EPOCH: 10

DECODER:
  BINARY: 2

# Config below only when you use comet
COMET:
  PROJECT_NAME: "CATDTI_CDAN"
  TAG: "DA"












